### ISSUE TITLE
Error 'engine.current.leaveChannel' 

### ISSUE THREAD

**Issue by davisuga** [AgoraIO-Community/ReactNative-UIKit#13]
Error 'engine.current.leaveChannel' shows when the component is mounted.
![bug](https://user-images.githubusercontent.com/33470530/92976014-f0f6d480-f45f-11ea-966a-56591a18ece7.PNG)

**Comment by technophilic** [comment]
Sorry for the delayed response, was the native module (Agora react native SDK) installed?

**Comment by technophilic** [comment]
I have updated the Readme to add more info around steps to run. Please let me know if this fixes your issue.

If not, Can you please fill out this template:

**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: [e.g. iPhone6]
 - OS:
   - [X] IOS
   - [ ] Android
 - OS Version: [e.g. 22, 14.1]

**App Info** (Note: Expo CLI managed workflow is not supported by the UIKit)
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI - bare workflow
 - CLI Version: [e.g. 22]

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.
