### ISSUE TITLE
Video is not showing on an ios device

### ISSUE THREAD

**Issue by ShadyStego** [AgoraIO-Community/ReactNative-UIKit#14]
I'm running the basic example with the <AgoraUIKit/> component. The 5 control buttons are displayed at the bottom, but the video is not displayed & the camera is not turned on. 
![Screenshot 2020-09-12 at 12 59 45 PM](https://user-images.githubusercontent.com/6054688/93003983-10d9d700-f4f8-11ea-8dbc-a942b316a3f1.png)

Here's what I see on the log:

```
2020-09-12 13:12:53.592 xcodebuild[12337:2070883] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs

2020-09-12 13:12:53.592 xcodebuild[12337:2070883] Failed to load plugin at: /Users/trisianto/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
```

**Comment by bdsumon4u** [comment]
#Video is not showing on android device also..
##It's showing a black screen.

**Comment by technophilic** [comment]
Sorry for the delayed response. I just tested out the application, it works fine and I'm able to see the video etc. I have updated the Readme to add more info around steps to run. Please let me know if this fixes your issue.

If not, Can you please fill out this template:

**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: [e.g. iPhone6]
 - OS:
   - [X] IOS
   - [ ] Android
 - OS Version: [e.g. 22, 14.1]

**App Info** (Note: Expo CLI managed workflow is not supported by the UIKit)
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI - bare workflow
 - CLI Version: [e.g. 22]

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by asadadams** [comment]
@bdsumon4u did you find a solution

**Comment by asadadams** [comment]
@technophilic I'm also getting a black screen , Any solution

**Comment by bdsumon4u** [comment]
> @bdsumon4u did you find a solution

I haven't tried it again.

**Comment by asadadams** [comment]
> > @bdsumon4u did you find a solution
> 
> I haven't tried it again.

O okay thanks, did you find any new service to implement the video call or you tried something elsee

**Comment by bdsumon4u** [comment]
> > > @bdsumon4u did you find a solution
> > 
> > 
> > I haven't tried it again.
> 
> O okay thanks, did you find any new service to implement the video call or you tried something elsee

Fortunately I got rid of video calling service from that project. So, I hadn't try anything else.

**Comment by technophilic** [comment]
If anybody else is facing the blank screen problem, please raise a new GitHub issue and fill up the issue template that helps us in debugging your issues. A blank screen can happen because of a number of reasons and without all the right information it is not possible to point out the problem.

**Comment by bipin-sakariya** [comment]
Yes video is not showing on an ios device.
