### ISSUE TITLE
Showing blank Screen.

### ISSUE THREAD

**Issue by abrarqureshi** [AgoraIO-Community/ReactNative-UIKit#15]
Not able to run this code only white blank screen showing.

**Comment by bdsumon4u** [comment]
I'm also having a black screen.

**Comment by technophilic** [comment]
Hey! I just tested out the application it works fine and I'm able to see the video etc. I have updated the Readme to add more info around steps to run. Please let me know if this fixes your issue.

If not, Can you please fill out this template:

**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: [e.g. iPhone6]
 - OS:
   - [X] IOS
   - [ ] Android
 - OS Version: [e.g. 22, 14.1]

**App Info** (Note: Expo CLI managed workflow is not supported by the UIKit)
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI - bare workflow
 - CLI Version: [e.g. 22]

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by duasfh** [comment]
only blank (white) screen too. Android version. Loggin works fine, but only showing white screen.
To reproduce -- only install and run
