### ISSUE TITLE
android - camera no working

### ISSUE THREAD

**Issue by thuantvDr4** [AgoraIO-Community/ReactNative-UIKit#56]
I install package and rebuild
but, on android camera is not work, only have black screen.
please support for me.
thanks

**Comment by EkaanshArora** [comment]
Can you fill this template?

**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: [e.g. iPhone6]
 - OS:
   - [X] IOS
   - [ ] Android
 - OS Version: [e.g. 22, 14.1]
 - UIKit Version: [eg 3.1.3]
 
**App Info**
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI (using custom development clients)
 - CLI Version: [e.g. 22]

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by thuantvDr4** [comment]
thanks @EkaanshArora replied.
my demo screen when running on android
device info:
name: Huawei Y7 Prime
OS: android - 7.0;
packages:
"agora-rn-uikit": "^3.3.0",
    "react": "17.0.2",
    "react-native": "0.67.4",
    "react-native-agora": "^3.5.3"

**Comment by thuantvDr4** [comment]
Great! 
I found root cause for the issue.
we must add token property for rtcProps
const rtcProps ={
   appId: '',
  channel: '',
 token: '',   // <--- this one
}
because, into guide usage base, not add.
![image](https://user-images.githubusercontent.com/24288310/159640215-96f6a714-4ac5-472d-ab5a-96cd28bd7357.png)


thank so much. I can close this issue
